# Makefile 

make: symbol.h alphabet.h chain.h language.h CyA_P03_Strings_Operation.cc 
	g++ CyA_P03_Strings_Operation.cc symbol.cc alphabet.cc chain.cc language.cc -o CyA_P03_Strings_Operation

clean:
	rm -f .out CyA_P03_Strings